name: Build on Tag

on:
  push:
    tags:
      - 'v*'
#    branches:
#      - main

permissions:
  contents: read

jobs:
  macos:
    strategy:
      matrix:
        os: [ macos-13, macos-latest ]
    uses: ./.github/workflows/_build-macos.yaml
    with:
      os: ${{ matrix.os }}

  windows:
    uses: ./.github/workflows/_build-windows.yaml

  linux:
    uses: ./.github/workflows/_build-linux.yaml

  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - macos
      - windows
      - linux
    if: ${{ needs.macos.result == 'success' && needs.windows.result == 'success' && needs.linux.result == 'success' }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4
        with:
          path: release
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R release

      - name: Generate SHA256SUMS
        run: |
          cd release
          sha256sum * > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda  # v2.2.1
        with:
          files: |
            release/*
          generate_release_notes: true
